# Generated by Django 5.0.6 on 2024-07-07 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('RouteId', models.AutoField(primary_key=True, serialize=False)),
                ('StartStation', models.CharField(max_length=500)),
                ('EndStation', models.CharField(max_length=500)),
                ('Distance', models.IntegerField()),
                ('DepartureTime', models.DateTimeField()),
                ('ArrivalTime', models.DateTimeField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('TicketCategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
                ('Firstname', models.CharField(max_length=500)),
                ('Lastname', models.CharField(max_length=500)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('TrainId', models.AutoField(primary_key=True, serialize=False)),
                ('TrainNumber', models.CharField(max_length=500)),
                ('Company', models.CharField(max_length=500)),
                ('RouteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfoTren.routes')),
            ],
        ),
        migrations.CreateModel(
            name='TrainSeats',
            fields=[
                ('SeatId', models.AutoField(primary_key=True, serialize=False)),
                ('SeatNumber', models.IntegerField()),
                ('Class', models.IntegerField()),
                ('IsBooked', models.BooleanField(default=False)),
                ('TrainId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfoTren.trains')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('TicketId', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IsPaid', models.BooleanField(default=False)),
                ('TicketCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfoTren.ticketcategory')),
                ('TrainId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfoTren.trains')),
                ('SeatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfoTren.trainseats')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfoTren.users')),
            ],
        ),
    ]
