# Generated by Django 5.0.6 on 2024-10-20 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoTren', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='BookingTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 20, 17, 24, 45, 133421, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
